### ISSUE TITLE
Error when compile uMQTT .

### ISSUE THREAD

**Issue by ShinDaiIchi** [sjs205/uMQTT#9]
I have tried to compile uMQTT,  but there's a problem, and return this error.

-----------------------------------------

......
gcc -c -Wall -Werror -I/home/esp8266/github/uMQTT/src/inc -O2 -DDEBUG -g -O0 uMQTT_tests.c -o /home/esp8266/github/uMQTT/bin/obj/uMQTT_tests.o
uMQTT_tests.c: In function ‘test_compare_packets’:
uMQTT_tests.c:99:33: error: self-comparison always evaluates to false [-Werror=tautological-compare]
   if (pkt1->fixed->generic.type != pkt1->fixed->generic.type) {
                                 ^~
cc1: all warnings being treated as errors
Makefile:27: recipe for target 'uMQTT_tests' failed
make[1]: *** [uMQTT_tests] Error 1
make[1]: Leaving directory '/home/esp8266/github/uMQTT/src/tests'
Makefile:44: recipe for target 'tests' failed
make: *** [tests] Error 2
--------------------------------------------------------------------------

How to solve the problem to compile ?
Thank you

**Comment by sjs205** [comment]
Hello,

I've never seen that error, but it is ovbiously a bug. I've fixed that now,
so if you pull the latest changes that should compile.

I hope that helps.

Many thanks for trying it.

sjs205
